### ISSUE TITLE
newsdev-wide webhook went missing?

### ISSUE THREAD

**Issue by tiffehr** [newsdev/lambda-gem-builder#2]
I have some lingering nytstdlib gem work that needed to be repackaged by Monday.  So I just pushed [`nytstdlib#v1.0.9`](https://github.com/newsdev/nytstdlib/releases/tag/v1.0.9) but didn't get my email confirmation of a successful build.

Looking at https://github.com/newsdev/lambda-gem-builder/wiki#lay-of-the-land, its link to the newsdev-wide webhook is no longer working, perhaps?  https://github.com/organizations/newsdev/settings/hooks/6386375

I can't get into our shared AWS (which is good, probably) to do more logging.  But even if the Lambda function is there and waiting, it wouldn't matter if the webhook isn't telling it things, correct?

Other details:
- `v1.0.8`, created yesterday (Friday), didn't build either, but I thought I'd messed it up, so I left it for today
- `v1.0.7` built fine as of 12/30/2015, says my email records

No rush on this.  It's just worth logging for...soon.  Tuesday, for sure, I'd like to be able to hit nytstdlib#v1.0.9.

**Comment by tiffehr** [comment]
Well, really, it's yours to close, @abstrctn.

**Comment by abstrctn** [comment]
Fixed by 4897e9c3aac127e6d360204939c60dd21bc13c05 :)
